# Generated by Django 2.2.6 on 2020-05-30 23:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('level', models.PositiveIntegerField()),
                ('time_needed', models.PositiveIntegerField()),
                ('price', models.FloatField()),
                ('is_free', models.BooleanField()),
                ('is_shared', models.BooleanField()),
                ('mind_master', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=128)),
                ('last_name', models.CharField(max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stars', models.PositiveIntegerField()),
                ('body', models.CharField(max_length=512)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('Course', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='API.Course', verbose_name='course')),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='API.User', verbose_name='user')),
            ],
        ),
        migrations.CreateModel(
            name='OwnedCourses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.PositiveIntegerField()),
                ('progress', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('Course', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='API.Course', verbose_name='course')),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='API.User', verbose_name='user')),
            ],
        ),
    ]
