# Generated by Django 2.2.6 on 2020-05-30 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='prof_pic',
            field=models.CharField(default='none', max_length=128),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='course',
            name='level',
            field=models.CharField(choices=[(0, 'zaaawansowany'), (1, 'średnio-zaawansowany'), (2, 'poczatkujacy')], default='unassigned', max_length=100),
        ),
    ]
